import Head from 'next/head'
import Topbar from '../src/components/Topbar/Topbar'
import HomePage from '../src/components/homePage/homePage'


export default function Home() {


  return (
    <div >
      <Head>
        <title>VITA | Respirador inteligente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        
      </Head>
      
      <main >
      <Topbar /> 
      <HomePage/>
      </main>
    </div>
  )
}


