version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
